-- Explory Data Analysis

USE flights;

SELECT *
FROM layoff_flight_2;

SELECT *
FROM layoff_flight_2
WHERE GENDER IS NULL;

SELECT MAX(AGE), MIN(AGE),AVG(AGE)
FROM layoff_flight_2;

SELECT GENDER, WORK_CITY
FROM layoff_flight_2
WHERE AGE = 12;

SELECT WORK_CITY, WORK_PROVINCE
FROM layoff_flight_2
WHERE WORK_PROVINCE IS NULL;

SELECT WORK_PROVINCE,GENDER, MAX(AGE), MIN(AGE), COUNT(WORK_PROVINCE) AS NUM
FROM layoff_flight_2
GROUP BY WORK_PROVINCE, GENDER 
ORDER BY NUM DESC, WORK_PROVINCE;

SELECT WORK_PROVINCE,  YEAR(FIRST_FLIGHT_DATE), COUNT(WORK_PROVINCE) AS NUM
FROM layoff_flight_2
GROUP BY WORK_PROVINCE, YEAR(FIRST_FLIGHT_DATE),GENDER 
ORDER BY NUM DESC, WORK_PROVINCE; 

WITH ROLLING_TOTAL AS
(
SELECT SUBSTRING(FIRST_FLIGHT_DATE,1,7) AS `MONTH`, COUNT(WORK_PROVINCE) AS AMOUNT
FROM layoff_flight_2
GROUP BY `MONTH`
ORDER BY 1 ASC
)
SELECT `MONTH`, COUNT(AMOUNT) OVER(ORDER BY `MONTH`) AS  ROLLING_TOTAL
FROM ROLLING_TOTAL;

WITH WORK_CITY AS
(
SELECT WORK_PROVINCE,  YEAR(FIRST_FLIGHT_DATE), COUNT(WORK_PROVINCE) AS NUM
FROM layoff_flight_2
GROUP BY WORK_PROVINCE, YEAR(FIRST_FLIGHT_DATE),GENDER 
ORDER BY NUM DESC, WORK_PROVINCE
)
SELECT *
FROM WORK_CITY;

WITH  WORK_PROVINCE_YEAR AS
(
SELECT WORK_PROVINCE,  YEAR(FIRST_FLIGHT_DATE), COUNT(WORK_PROVINCE) AS NUM
FROM layoff_flight_2
GROUP BY WORK_PROVINCE, YEAR(FIRST_FLIGHT_DATE) 
), WORK_PROVINCE_YEAR_RANK AS
( SELECT *,
DENSE_RANK() OVER (PARTITION BY  YEAR(FIRST_FLIGHT_DATE) ORDER BY  WORK_PROVINCE DESC) AS RANKING
FROM  WORK_PROVINCE_YEAR
WHERE WORK_PROVINCE IS NOT NULL
ORDER BY NUM DESC
)
SELECT*
FROM  WORK_PROVINCE_YEAR ;

WITH  WORK_PROVINCE_YEAR_2 (PROVINCE, YEARS, AMOUNT) AS
(
SELECT WORK_PROVINCE,  YEAR(FIRST_FLIGHT_DATE), COUNT(WORK_PROVINCE) AS NUM
FROM layoff_flight_2
GROUP BY WORK_PROVINCE, YEAR(FIRST_FLIGHT_DATE) 
),WORK_PROVINCE_YEAR_RANK AS (
 SELECT *,
DENSE_RANK() OVER (PARTITION BY PROVINCE  ORDER BY YEARS DESC) AS RANKING
FROM  WORK_PROVINCE_YEAR_2
)
SELECT*
FROM  WORK_PROVINCE_YEAR_RANK
 WHERE RANKING <=5


